export const RESET_STATE = 'AUTH_RESET_STATE';
export const UPDATE_USER_NAME = 'AUTH_UPDATE_USER_NAME';
export const UPDATE_REFRESH_TOKEN = 'AUTH_UPDATE_REFRESH_TOKEN';
export const UPDATE_ACCESS_TOKEN = 'AUTH_UPDATE_ACCESS_TOKEN';
export const UPDATE_VOTE_STATUS = 'AUTH_UPDATE_VOTE_STATUS';
